version: '3.4'
services:
  osticket-db:
    image: mysql:8.0.4
    container_name: osticket-db
    hostname: osticket-db
    restart: unless-stopped
    ports:
      - 3309:3306
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    env_file: .env
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - ./osticket/db:/var/lib/mysql
#    networks:
#      - services

  osticket-app:
    image: devinsolutions/osticket:1.17.2
    container_name: osticket-app
    hostname: osticket-app
    restart: unless-stopped
    ports:
      - 5335:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    volumes:
      - ./osticket/data/plugins:/var/www/html/include/plugins
      - ./osticket/data/scp.css:/var/www/html/scp/css/scp.css
    depends_on:
      - osticket-db
    env_file: .env
#    networks:
#      - services
#      - nginx-proxy

#networks:
#  services:
#    external: true
#  nginx-proxy:
#    external: true
