version: '3.4'
services:
  osticket-db:
    container_name: osticket-db
    hostname: osticket-db
    restart: unless-stopped
    image: mysql:5.7.22
    env_file: .env
    volumes:
      - ./osticket/db:/var/lib/mysql
    networks:
      - services

  osticket-app:
    container_name: osticket-app
    hostname: osticket-app
    restart: unless-stopped
    image: devinsolutions/osticket:1.16.3
    depends_on:
      - mysql
    env_file: .env
    ports:
    - 5335:80
    networks:
      - services

networks:
  services:
    external: true
