version: '3.4'
services:
  osticket-db:
    image: mysql:8.0.4
#    image: mysql:5.7.22
    container_name: osticket-db
    hostname: osticket-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    env_file: .env
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - ./osticket/db:/var/lib/mysql
    networks:
      - services

  osticket-app:
    image: devinsolutions/osticket:1.16.3
    container_name: osticket-app
    hostname: osticket-app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    depends_on:
      - osticket-db
    env_file: .env
    ports:
      - 5335:80
    networks:
      - services

networks:
  services:
    external: true
